# Notes


I was confused when I had to write the test, but I figured out in the end.
And apparently I wasn't working on the latest version of python-zulip-api, took me a while to get the latest version.
And when I ran the test, python collided with Anaconda3 so I uninstalled it. It worked fine after.
I'm glad to finish this task in the end.