I had some problems while running the bot like ImportError and errors like "No such file or directory",
but was later solved by recloning the repo. I also had a problem while testing, but the problem was solved by deleting
the "test_message_info.py" file and recreating it.
